name: Test

on:
  push:
    paths:
      - "src/**/*.java"
      - "build.gradle.kts"
      - "gradle/**"
      - ".github/workflows/*.yaml"
  pull_request:
    paths:
      - "src/**/*.java"
      - "build.gradle.kts"
      - "gradle/**"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Codecovがプルリクエストにコメントするために必要

    steps:
    - name: Checkout code
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        fetch-depth: 0 # Codecovが正しく動作するために履歴全体を取得

    - name: Set up Java 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Run tests with coverage
      run: ./gradlew test jacocoTestReport && ls build/reports/jacoco/test/jacocoTestReport.xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1

    - name: Archive test results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: always()
      with:
        name: test-results
        path: |
          build/reports/tests/
          build/reports/jacoco/

